### ISSUE TITLE
Add XP Storage

### ISSUE THREAD

**Issue by thorbaert** [JoshuaBaert/mc-node-wrapper#20]
It would be awesome if there could be a way to store your level. That way if you knew you were going to do something dangerous you could store your experience with the server.

Commands like: 
`!xp store` puts all your current xp in storage 
`!xp list` displays how much you have stored
`!xp get` gives you your xp.
maybe even `!xp get ###` with some amount being how much you'd like to get

@Gobsmack90 what do you think of this?

**Comment by Gobsmack90** [comment]
Well that sounds amazing but pretty overpowered?

You can just keep storing your xp every few levels and only take it out when you're going to enchant, etc.

So there's really no danger involved in exploring anymore, yes you can lose gear but xp is the most valuable thing you lose when you die, imo.

So my question is how can we keep something so powerful in check? Cooldowns are an option but I think they'll have to be really long cooldowns and that still may not be enough.

What do you think?

**Comment by thorbaert** [comment]
Maybe we implement a database driven cooldown with a much longer time between uses.. Like 2 weeks or something.. We can also add the cooldown to just storing?

Honestly Losing the gear for me is much more valuable.. and particually once you start enchanting more weapons and armor if you've got 10 levels in 1 piece of equipment the equipment is super more valuable.. 

But it might seem over powered to save up all your xp but honestly I kinda want to give people the ability to get more enchants quicker.

**Comment by Gobsmack90** [comment]
That's a good point about the enchanted gear. A two week cooldown might be the right call

**Comment by thorbaert** [comment]
Honestly with the talk of helping people get enchanted gear I'd almost want a shorter cooldown

**Comment by Gobsmack90** [comment]
I'm kinda thinking the same thing haha
