### ISSUE TITLE
Add list and define argument on each command.

### ISSUE THREAD

**Issue by Gobsmack90** [JoshuaBaert/mc-node-wrapper#22]
so that players can see all the options and descriptions of each option. they have on it.

`player: !home list
server: set, location 1`

`player: !home define
server: can set a home to warp to by typing !home set, can warp to the location set as your home after a 30 minute cooldown by typing !home.`

**Comment by thorbaert** [comment]
We should have that you can type `!help` to get a list of commands

Also need to figure out a way to setup each commands abstraction or way of adding to this `!help` block

**Comment by thorbaert** [comment]
To be more specific I want to add the command `!help` that will give you a general listing of the commands available

Then `!help home` would give greater details to the options with warp

**Comment by Gobsmack90** [comment]
that sounds good.
