### ISSUE TITLE
Add !Locations

### ISSUE THREAD

**Issue by thorbaert** [JoshuaBaert/mc-node-wrapper#4]
It would be nice to be able to add Named locations. like `!HelloCity` that allows the player to teleport to common locations around the world.

Would be a place for discussion as to how these locations are created and saved. Right now there is no Authorization so right off the bat anyone could add a new location which would not be a desirable outcome. We may need to add some type of 'node admin' or saves in the database to set who can or can't add new locations. Or maybe if we hard code them not sure.

**Comment by Gobsmack90** [comment]
In addition to this it would be nice if players could create personal locations to warp to. we could allow as many as we want but i'm thinking 5 to start. that way i can warp to your house, my mine, the starting village, etc.

it can all be on the same cooldown as home or on a separate cooldown.

something like:

///player: !location 1 set

//if no conflict:
server: location 1 set to ${coordinates}

//if conflict:
server: location 1 is already set, replace? y/n
player: y
server: location 1 set to ${coordinates}///

**Comment by thorbaert** [comment]
Yeah I think we could do this I might want to include it in the home command like

`!home set mine`
`!home mine`

That way it will be easier to add them to the same cooldown 

We'd also have to add something like

`!home remove mine`

**Comment by Gobsmack90** [comment]
so we'd have it so we can name our own home locations?

so i could go `!home set josh` at your place and it would warp me there?

we'd need to have a way to limit the amount of locations you can place. I imagine a server message going:

server: `home josh set at location ${} you have 3 available home locations you can set`

**Comment by thorbaert** [comment]
Yeah it would be specific to each player your home  mine would not be for me

**Comment by Gobsmack90** [comment]
here's a different idea: what if we merged all commands related to teleporting under `!warp`, including !home.

pros: 
- its cleaner to have everything related to teleporting under one command. less duplicate code and stuff.
- in my opinion, its more intuitive to say `!warp home` or `!warp joshhome` or !warp mine` than `!home mine`
- if we forget the name of a location we can type `!warp list` to list them all, and we could then include the player locations and the server locations.

cons:
- it takes longer to warp home than simply typing !home
