### ISSUE TITLE
all commands currently ignore extra args when player inputs too many

### ISSUE THREAD

**Issue by Gobsmack90** [JoshuaBaert/mc-node-wrapper#56]
for example:
`!warp accept all yes` registers as `!warp accept all`
`!warp queue d` registers as `!warp queue`
this is present in the commands you've made too,
`!home set home2 extraword` registers as `!home set home2`

we haven't programmed in any instructions on what to do if a player does such a thing. this may be something we want to fix later on

**Comment by thorbaert** [comment]
After discussion this doesn't seem to bug us too much
